apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-native-config
data:
  application.yml: |
    demo:
      message: Welcome to Spring Native on Kubernetes!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus
      metrics:
        tags:
          application: ${spring.application.name}
